### ISSUE TITLE
- (UIViewController *)viewPager:(ViewPagerController *)viewPager contentViewControllerForTabAtIndex:(NSUInteger)index giving incorrect index

### ISSUE THREAD

**Issue by vuevrn** [iltercengiz/ICViewPager#100]
- (UIViewController *)viewPager:(ViewPagerController *)viewPager contentViewControllerForTabAtIndex:(NSUInteger)index
{
    NSLog("%d",index);

    return [self.arrViews objectAtIndex:index];
}

when sliding or selecting any tab, initially it shows right index but then in starts showing incorrect index. 

P.S.
But the funny thing is it returns the view controller of the correct index. It just shows incorrect index and not view controller.

**Comment by mihirbgurjar** [comment]
## Below Code will get you correct index number. :)
- (void)viewPager:(ViewPagerController *)viewPager didChangeTabToIndex:(NSUInteger)index
  {
  
  NSInteger *ab=index;
  }

**Comment by vuevrn** [comment]
well I sort of had found a work around in those days. I should go through the library and the methods. Anyways thanks.
