### ISSUE TITLE
20 PX jerk in Navigation Controller 

### ISSUE THREAD

**Issue by asifhabib** [iltercengiz/ICViewPager#102]
![ios simulator screen shot jan 17 2015 6 19 43 pm](https://cloud.githubusercontent.com/assets/3713433/5788940/c4b18efa-9e76-11e4-9e50-73eb0327a633.png)
![ios simulator screen shot jan 17 2015 6 19 44 pm](https://cloud.githubusercontent.com/assets/3713433/5788939/c4af7a52-9e76-11e4-871e-6adf02e23528.png)

When some view is pushed form ICViewpager, and when we come back to the ICViewPager by poping the view, content view is 20 pixel down from its orignal position, which instantly go back to its orignal positions!

**Comment by BillHu** [comment]
Same here, mine just don't go back to its orignal positions.
any idea?

**Comment by asifhabib** [comment]
I resolved my problem by unchecking `Adjust Scroll View Insets` in `View Controllers`
You can disable it programmatically too. It resolved many other problems too :)
