### ISSUE TITLE
speed the launch up

### ISSUE THREAD

**Issue by HollyMadCow** [iltercengiz/ICViewPager#117]
when I launch this demo， The view freeze and not show all components up in the first seconds，
I must wait seconds for it 

the experience is not the best ：）

**Comment by mihirbgurjar** [comment]
## Replace Your Code With Below Code. (HostViewController.m)
- (void)viewDidAppear:(BOOL)animated {
  
  [super viewDidAppear:animated];
  
  [self performSelector:@selector(loadContent) withObject:nil afterDelay:0.0];

}

**Comment by iltercengiz** [comment]
This is to simulate data loading. just call `[self loadContent];` instead of that line.
