### ISSUE TITLE
it makes me confused when i slide to the second VC, the method - (void)viewDidLoad of the third VC gets called??

### ISSUE THREAD

**Issue by fsresponser** [iltercengiz/ICViewPager#124]
ICViewPager is a great class, and i recently use it in my project. just as the title says, it makes me confused when i slide to the second VC, the method - (void)viewDidLoad of the third VC (or even the fourth ... )gets called??   can you help me out. thank you !

**Comment by iltercengiz** [comment]
It's the intended behaviour, because of caching and managing view controllers. See UIPageViewController class for more.
