### ISSUE TITLE
How to make the width of the tabs dinamic??

### ISSUE THREAD

**Issue by RafaRuiz** [iltercengiz/ICViewPager#129]
I'd like to know how to change the width of the tabs dinamically since they have different content:
![image](https://cloud.githubusercontent.com/assets/6842786/9568420/78afcabe-4f40-11e5-9eed-4bb15569d334.png)

There's a method where you can change the label yourself:

`- (UIView *)viewPager:(ViewPagerController *)viewPager viewForTabAtIndex:(NSUInteger)index {
}`

but I've tried to use:
`
CGSize expectedLabelSize = [titleString sizeWithFont:label.font
                                  constrainedToSize:CGSizeMake(400,200)
                                      lineBreakMode:label.lineBreakMode];
    [label sizeThatFits:expectedLabelSize];
`

and it doesn't work (nothing appears).

Does anyone have a clue?

Thank you very much in advance.

**Comment by iltercengiz** [comment]
This feature is under development with version 2.0.
