### ISSUE TITLE
Dynamic size for tabs

### ISSUE THREAD

**Issue by thailey01** [iltercengiz/ICViewPager#141]
Hello,

I love this library. However, I was wondering if there's some way of making the numberOfTabs method wait for the program to fetch a list from the cloud? The list from the cloud determines the number of tabs and that list could change at any moment so it has to exist on the cloud. Any help would be great. Thank you.

**Comment by iltercengiz** [comment]
Sorry for very late reply, but if the content lives on an API, you need to fetch it first then configure your data source. Hope you've solved it by now already.
