### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by manicmaniac** [iltercengiz/ICViewPager#145]
Hi @iltercengiz, Is the project abandoned?

**Comment by seyfeddin** [comment]
@manicmaniac we haven't abandoned, but both our work schedules are very tight right now.

**Comment by batuhankok** [comment]
Hey @manicmaniac, I have a good news for you, there will be new version of ICViewPager here as soon as possible ☺️

**Comment by jvanakker** [comment]
But now officially abandoned?

**Comment by iltercengiz** [comment]
Version 2.0 is in development. You can check the progress from reincarnation branch. 😊
