### ISSUE TITLE
Top layout adds a gap on iOS 8

### ISSUE THREAD

**Issue by jefflen** [iltercengiz/ICViewPager#88]
Top layout adds a gap on iOS 8 and I have to remove the following line to fix this.
- (void)layoutSubviews {
  
  CGFloat topLayoutGuide = 0.0;
  /\* I have to remove these lines to fix the layout issue on iOS 8
  if (IOS_VERSION_7) {
      topLayoutGuide = 20.0;
      if (self.navigationController && !self.navigationController.navigationBarHidden) {
          topLayoutGuide += self.navigationController.navigationBar.frame.size.height;
      }
  }
  */
  ...

**Comment by wilsontgh** [comment]
I fixed this by checking the Extend Edges: Under Opaque Bars checkbox. (edgesForExtendedLayout extendedLayoutIncludesOpaqueBars)
